name: Update Points Workflow

on:
  issues:
    types:
      - closed

jobs:
  updatePoints:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Extract Label Information
        run: |
          # Extract label information from the event payload
          labels=$(jq -r '.issue.labels[].name' "$GITHUB_EVENT_PATH")

          # Extract issueID and points from labels
          issueID=$(echo "$labels" | sed -nE 's/issueID:([0-9]+)/\1/p')
          points=$(echo "$labels" | sed -nE 's/points:([0-9]+)/\1/p')
          username=$(jq -r '.issue.assignee.login' "$GITHUB_EVENT_PATH")

          # Output the extracted information for debugging
          echo "Issue ID: $issueID"
          echo "Points: $points"
          echo "Username: $username"

      - name: Update Points
        run: |
          # Make a POST request to your API endpoint using extracted information
          API_DOMAIN=${{ secrets.API_DOMAIN }}
          curl -X POST -H "Content-Type: application/json" \
            -d "{\"issueID\": $(echo "$issueID" | jq -R . || echo null), \"points\": $(echo "$points" | jq -R . || echo null), \"username\": \"$username\"}" \
            $API_DOMAIN/points

        # Add more steps as needed
