name: Update Points Workflow

on:
  issues:
    types:
      - closed

jobs:
  updatePoints:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Run Update Points Script
        run: |
          npm install # Install dependencies if needed
          node scrpits/updatePoints.js
        env:
          INPUT_ISSUE_ID: ${{ steps.extract.outputs.issueID }}
          INPUT_POINTS: ${{ steps.extract.outputs.points }}
          INPUT_USERNAME: ${{ steps.extract.outputs.username }}

      - name: Extract Label Information
        id: extract
        run: |
          labels=$(jq -r '.issue.labels[].name' "$GITHUB_EVENT_PATH")
          issueID=$(echo "$labels" | sed -nE 's/issueID:([0-9]+)/\1/p')
          points=$(echo "$labels" | sed -nE 's/points:([0-9]+)/\1/p')
          username=$(jq -r '.issue.assignee.login' "$GITHUB_EVENT_PATH")
          echo "::set-output name=issueID::$issueID"
          echo "::set-output name=points::$points"
          echo "::set-output name=username::$username"

      # Add more steps as needed
