name: Update Points Workflow

on:
    workflow_dispatch:
    pull_request:
        types: [closed]

jobs:
  updatePoints:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Extract Label Information
        run: |
          
          labels=$(jq -r '.pull_request.labels[].name' "$GITHUB_EVENT_PATH")

          
          issueID=$(echo "$labels" | sed -nE 's/issueID:([0-9]+)/\1/p')
          points=$(echo "$labels" | sed -nE 's/points:([0-9]+)/\1/p')
          prNumber=$(jq -r '.pull_request.number' "$GITHUB_EVENT_PATH")

          
          echo "Issue ID: $issueID"
          echo "Points: $points"
          echo "PR Number: $prNumber"

      - name: Update Points
        run: |
          
          API_DOMAIN=${{ secrets.API_DOMAIN }}
          curl -X POST -H "Content-Type: application/json" \
               -d "{\"issueID\": $issueID, \"points\": $points, \"prNumber\": $prNumber}" \
               $API_DOMAIN/points
        
        
